name: Build the application and run the tests

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:
  build_and_test_the_app:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET v6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the application
      run: dotnet build --no-restore
      
    - name: Run the all tests
      run: dotnet test --no-build --verbosity normal
